apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dc-app-01-poc-d-dev
  namespace: argocd
  labels:
    app: dc-app-01
    team: team-c
    component: backend
    environment: poc-d-dev
    cluster: t3d
    app-type: dc-app
spec:
  project: default
  source:
    repoURL: https://github.com/tsboris/gitops.git
    targetRevision: HEAD
    path: gitops/poc-app-of-apps/apps/t3/dc-app-01
    helm:
      valueFiles:
        - ../../../environments/poc-d-dev/values/dc-app-01.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: poc-d-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 