{{/* Simple application loading from config file */}}
{{- $applications := list -}}

{{/* Load applications from either direct values or config file */}}
{{- if .Values.applications -}}
  {{- $applications = .Values.applications -}}
{{- else if .Values.configFileContent -}}
  {{- $configData := .Values.configFileContent | fromYaml -}}
  {{- if hasKey $configData "applications" -}}
    {{- $applications = $configData.applications -}}
  {{- end -}}
{{- end -}}

{{/* Generate Application resources */}}
{{ range $app := $applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: {{ $app.namespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: {{ $app.name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    {{- with $app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  project: {{ $app.project | default "default" }}
  source:
    repoURL: {{ $app.repoURL | default $.Values.repoURL }}
    targetRevision: {{ $app.targetRevision | default "HEAD" }}
    {{- if $app.chart }}
    chart: {{ $app.chart }}
    {{- with $app.helm }}
    helm:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- else -}}
    path: {{ $app.path }}
    {{- with $app.helm }}
    helm:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  destination:
    server: {{ $app.server | default "https://kubernetes.default.svc" }}
    namespace: {{ $app.namespace | default "default" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  {{- with $app.ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $app.info }}
  info:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 