apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-environment
  namespace: argocd
  labels:
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/tsboris/gitops.git
    targetRevision: HEAD
    path: gitops/poc-app-of-apps/environments/dev/applications
    directory:
      include: "*.yaml"
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 