replicaCount: 1

image:
  repository: busybox
  tag: "1.36"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 50m
    memory: 16Mi
  requests:
    cpu: 10m
    memory: 8Mi

command: ["sh", "-c", "while true; do sleep 3600; done"]
