apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: t2-applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/tsboris/gitops.git
      revision: HEAD
      directories:
      - path: poc-d-gitops/apps/t2/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tsboris/gitops.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - ../../env/poc-d-dev/values.yaml
      destination:
        server: https://kubernetes.default.svc
        name: t2d
        namespace: poc-d-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true 