apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: t3-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/borist/test-code.git
        targetRevision: HEAD
        directories:
          - path: poc-d-gitops/apps/t3/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/borist/test-code.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: poc-d-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 