apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stress-t2-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tsboris/gitops.git
        revision: HEAD
        files:
          - path: poc-d-gitops/env/poc-d-stress/cluster-t2.yaml
  template:
    metadata:
      labels:
        version: "{{prodBundleVersion}}"
      name: "{{serviceName}}"
    spec:
      project: default
      source:
        repoURL: {{serviceGitRepo}}
        targetRevision: HEAD
        path: "helm-chart"
        helm:
          valueFiles:
            - values-qa.yaml
          parameters:
            - name: image.tag
              value: "{{serviceImageTag}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{serviceNamespace | default 'poc-d-stress-bff'}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true 
        syncOptions:
          - CreateNamespace=true